import Position from '../util/Position';

const p = Position;

export const fatal2x3Seed7NoLegalMove = {
  name: 'fatal 2x3 seed 7 stationary-growth trap',
  board: { numRows: 2, numCols: 3, wallsAreFatal: true },
  seed: 7,
  maxFrames: 100,
  foodTrace: [p(0, 1), p(2, 0), p(0, 0), p(0, 1), p(2, 0)],
  expected: {
    outcome: 'noLegalMove',
    frameCount: 11,
    score: 4,
    food: p(2, 0),
    snake: {
      direction: p(0, 1),
      parts: [p(0, 1), p(0, 0), p(1, 0), p(1, 1), p(1, 1)],
    },
  },
};

export const fatal6x6Seed0NoLegalMove = {
  name: 'fatal 6x6 seed 0 final-food stationary-growth trap',
  board: { numRows: 6, numCols: 6, wallsAreFatal: true },
  seed: 0,
  maxFrames: 2000,
  foodTrace: [
    p(3, 0),
    p(3, 5),
    p(1, 4),
    p(4, 4),
    p(3, 0),
    p(0, 3),
    p(5, 5),
    p(0, 5),
    p(1, 5),
    p(1, 1),
    p(5, 3),
    p(5, 5),
    p(4, 1),
    p(3, 2),
    p(1, 4),
    p(4, 0),
    p(5, 1),
    p(1, 5),
    p(1, 3),
    p(4, 4),
    p(2, 3),
    p(5, 5),
    p(4, 5),
    p(1, 5),
    p(4, 2),
    p(0, 1),
    p(4, 1),
    p(2, 4),
    p(3, 0),
    p(4, 5),
    p(2, 5),
    p(5, 5),
    p(4, 5),
    p(3, 5),
    p(4, 4),
  ],
  expected: {
    outcome: 'noLegalMove',
    frameCount: 238,
    score: 34,
    food: p(4, 4),
    direction: p(-1, 0),
    head: p(3, 5),
    duplicatedTail: p(2, 5),
  },
};
